<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [ ]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [ ]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.rand((5,6))

tensor([[0.0411, 0.1285, 0.3346, 0.8913, 0.5452, 0.6047],
        [0.3333, 0.9102, 0.9964, 0.8492, 0.6957, 0.6937],
        [0.7065, 0.6974, 0.7664, 0.4940, 0.2939, 0.9721],
        [0.4029, 0.1726, 0.4479, 0.2567, 0.2710, 0.4928],
        [0.1171, 0.6376, 0.1387, 0.4753, 0.0440, 0.8749]])

In [ ]:
x = torch.arange(6)
x = x.reshape(2, 3)

In [ ]:
x.view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x = torch.arange(8)
y = torch.arange(8)
x = x.reshape(2,4)
y = y.reshape(4,2)
print(torch.matmul(x,y))

tensor([[28, 34],
        [76, 98]])


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


cuda


In [ ]:
x.to("cuda")

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], device='cuda:0')

In [ ]:
y.to("cpu")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [ ]:
torch.matmul(x,y)

tensor([[28, 34],
        [76, 98]])

In [ ]:
print(x.device)

cpu


In [ ]:
x = torch.rand((2,3), requires_grad=True)
y= x**2
z = y.sum()
z.backward()

print(x)
print(x.grad)

tensor([[0.2117, 0.8999, 0.9021],
        [0.2008, 0.1164, 0.8587]], requires_grad=True)
tensor([[0.4235, 1.7998, 1.8041],
        [0.4015, 0.2328, 1.7174]])


In [ ]:
import torch

# Data
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

# Model parameters
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training loop
for i in range(100):
    # Forward
    y_pred = w * x + b

    # Loss (MSE)
    loss = ((y_pred - y)**2).mean()

    # Backward
    loss.backward()

    # Update weights
    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad

    # Zero gradients
    w.grad.zero_()
    b.grad.zero_()

print(w, b)

tensor([1.8416], requires_grad=True) tensor([1.3600], requires_grad=True)


In [ ]:
import torch.nn as nn
import torch.optim as optim

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

model = nn.Linear(1,1)

optimizer = optim.Adam(model.parameters() , lr = 0.01)

criterion = nn.MSELoss()

for i in range(100):
  y_pred = model(x)
  loss = criterion(y_pred , y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

print(list(model.parameters()))

[Parameter containing:
tensor([[1.7718]], requires_grad=True), Parameter containing:
tensor([0.6225], requires_grad=True)]


In [35]:
from torch.utils.data import DataLoader

class Dataset:
  def __init__(self , x,y):
    self.x = x
    self.y = y

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = Dataset([1,2,3,4,5] , [2,4,6,8,10])

loader = DataLoader(dataset=dataset ,batch_size=2 , shuffle = True)

for x,y in loader:
  print(x,y)


In [50]:
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

class DataSet:
  def __init__(self):
    self.x = torch.randn(100, 10)
    self.y = torch.randint(0, 3, (100,))

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = DataSet()

loader = DataLoader( dataset,batch_size=2 , shuffle=True)

model = nn.Linear(10, 3)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters() , lr=0.01)

for epoch in range(100):
  epoch_loss =0
  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred , y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_loss += loss.item()
  print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}")

#Validation

  val_loss =0

  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred , y)
    val_loss += loss.item()
  print(f"""val_loss for epoch{i} is {val_loss}""")





Epoch 1, Loss: 58.3782
val_loss for epoch99 is 53.76974034309387
Epoch 2, Loss: 54.2830
val_loss for epoch99 is 51.58463940024376
Epoch 3, Loss: 53.1246
val_loss for epoch99 is 50.90380847454071
Epoch 4, Loss: 52.4213
val_loss for epoch99 is 50.59126776456833
Epoch 5, Loss: 52.5589
val_loss for epoch99 is 50.40505796670914
Epoch 6, Loss: 51.6740
val_loss for epoch99 is 50.35405510663986
Epoch 7, Loss: 52.2923
val_loss for epoch99 is 50.27779346704483
Epoch 8, Loss: 51.7718
val_loss for epoch99 is 50.25981593132019
Epoch 9, Loss: 51.7580
val_loss for epoch99 is 50.23574423789978
Epoch 10, Loss: 51.7318
val_loss for epoch99 is 50.25051838159561
Epoch 11, Loss: 51.8794
val_loss for epoch99 is 50.25836378335953
Epoch 12, Loss: 51.9603
val_loss for epoch99 is 50.24539923667908
Epoch 13, Loss: 51.9762
val_loss for epoch99 is 50.27438235282898
Epoch 14, Loss: 51.7493
val_loss for epoch99 is 50.260154753923416
Epoch 15, Loss: 51.9133
val_loss for epoch99 is 50.28095555305481
Epoch 16, Loss: 51