<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [ ]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [ ]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.rand((5,6))

tensor([[0.0411, 0.1285, 0.3346, 0.8913, 0.5452, 0.6047],
        [0.3333, 0.9102, 0.9964, 0.8492, 0.6957, 0.6937],
        [0.7065, 0.6974, 0.7664, 0.4940, 0.2939, 0.9721],
        [0.4029, 0.1726, 0.4479, 0.2567, 0.2710, 0.4928],
        [0.1171, 0.6376, 0.1387, 0.4753, 0.0440, 0.8749]])

In [ ]:
x = torch.arange(6)
x = x.reshape(2, 3)

In [ ]:
x.view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x = torch.arange(8)
y = torch.arange(8)
x = x.reshape(2,4)
y = y.reshape(4,2)
print(torch.matmul(x,y))

tensor([[28, 34],
        [76, 98]])


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


cuda


In [ ]:
x.to("cuda")

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], device='cuda:0')

In [ ]:
y.to("cpu")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [ ]:
torch.matmul(x,y)

tensor([[28, 34],
        [76, 98]])

In [ ]:
print(x.device)

cpu


In [ ]:
x = torch.rand((2,3), requires_grad=True)
y= x**2
z = y.sum()
z.backward()

print(x)
print(x.grad)

tensor([[0.2117, 0.8999, 0.9021],
        [0.2008, 0.1164, 0.8587]], requires_grad=True)
tensor([[0.4235, 1.7998, 1.8041],
        [0.4015, 0.2328, 1.7174]])


In [ ]:
import torch

# Data
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

# Model parameters
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training loop
for i in range(100):
    # Forward
    y_pred = w * x + b

    # Loss (MSE)
    loss = ((y_pred - y)**2).mean()

    # Backward
    loss.backward()

    # Update weights
    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad

    # Zero gradients
    w.grad.zero_()
    b.grad.zero_()

print(w, b)

tensor([1.8416], requires_grad=True) tensor([1.3600], requires_grad=True)


In [ ]:
import torch.nn as nn
import torch.optim as optim

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

model = nn.Linear(1,1)

optimizer = optim.Adam(model.parameters() , lr = 0.01)

criterion = nn.MSELoss()

for i in range(100):
  y_pred = model(x)
  loss = criterion(y_pred , y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

print(list(model.parameters()))

[Parameter containing:
tensor([[1.7718]], requires_grad=True), Parameter containing:
tensor([0.6225], requires_grad=True)]


In [35]:
from torch.utils.data import DataLoader

class Dataset:
  def __init__(self , x,y):
    self.x = x
    self.y = y

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = Dataset([1,2,3,4,5] , [2,4,6,8,10])

loader = DataLoader(dataset=dataset ,batch_size=2 , shuffle = True)

for x,y in loader:
  print(x,y)


In [48]:
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

class DataSet:
  def __init__(self):
    self.x = torch.randn(100, 10)
    self.y = torch.randint(0, 3, (100,))

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = DataSet()

loader = DataLoader( dataset,batch_size=2 , shuffle=True)

model = nn.Linear(10, 3)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters() , lr=0.01)

for epoch in range(100):
  epoch_loss =0
  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred , y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_loss += loss.item()
  print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}")





Epoch 1, Loss: 60.4081
Epoch 2, Loss: 51.6145
Epoch 3, Loss: 49.4553
Epoch 4, Loss: 48.2732
Epoch 5, Loss: 48.1159
Epoch 6, Loss: 48.0711
Epoch 7, Loss: 47.3720
Epoch 8, Loss: 47.8326
Epoch 9, Loss: 47.8320
Epoch 10, Loss: 47.6277
Epoch 11, Loss: 47.6472
Epoch 12, Loss: 47.5096
Epoch 13, Loss: 47.5112
Epoch 14, Loss: 47.6473
Epoch 15, Loss: 47.4293
Epoch 16, Loss: 47.8913
Epoch 17, Loss: 47.2961
Epoch 18, Loss: 47.4894
Epoch 19, Loss: 47.5733
Epoch 20, Loss: 47.6206
Epoch 21, Loss: 47.3235
Epoch 22, Loss: 47.2733
Epoch 23, Loss: 47.3084
Epoch 24, Loss: 47.9178
Epoch 25, Loss: 47.3904
Epoch 26, Loss: 47.5594
Epoch 27, Loss: 47.2678
Epoch 28, Loss: 48.1373
Epoch 29, Loss: 47.6242
Epoch 30, Loss: 47.3193
Epoch 31, Loss: 47.4567
Epoch 32, Loss: 47.4487
Epoch 33, Loss: 47.7137
Epoch 34, Loss: 47.3012
Epoch 35, Loss: 47.3469
Epoch 36, Loss: 47.6677
Epoch 37, Loss: 47.5528
Epoch 38, Loss: 47.2376
Epoch 39, Loss: 47.2490
Epoch 40, Loss: 47.5792
Epoch 41, Loss: 47.2257
Epoch 42, Loss: 47.4619
E