<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import torch

In [46]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [47]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [48]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [49]:
torch.rand((5,6))

tensor([[0.1647, 0.6469, 0.4940, 0.2430, 0.9584, 0.7887],
        [0.6675, 0.6654, 0.9684, 0.4228, 0.0113, 0.9797],
        [0.9406, 0.1950, 0.8800, 0.3288, 0.9358, 0.0747],
        [0.5365, 0.9462, 0.3053, 0.5928, 0.0578, 0.3124],
        [0.8588, 0.3180, 0.0730, 0.9461, 0.1814, 0.4768]])

In [50]:
x = torch.arange(6)
x = x.reshape(2, 3)

In [51]:
x.view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [52]:
x = torch.arange(8)
y = torch.arange(8)
x = x.reshape(2,4)
y = y.reshape(4,2)
print(torch.matmul(x,y))

tensor([[28, 34],
        [76, 98]])


In [53]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


cuda


In [54]:
x.to("cuda")

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], device='cuda:0')

In [55]:
y.to("cpu")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [56]:
torch.matmul(x,y)

tensor([[28, 34],
        [76, 98]])

In [57]:
print(x.device)

cpu


In [58]:
x = torch.rand((2,3), requires_grad=True)
y= x**2
z = y.sum()
z.backward()

print(x)
print(x.grad)

tensor([[0.2934, 0.3682, 0.1464],
        [0.9161, 0.7019, 0.0443]], requires_grad=True)
tensor([[0.5868, 0.7363, 0.2929],
        [1.8323, 1.4039, 0.0887]])


In [59]:
import torch

# Data
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

# Model parameters
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training loop
for i in range(100):
    # Forward
    y_pred = w * x + b

    # Loss (MSE)
    loss = ((y_pred - y)**2).mean()

    # Backward
    loss.backward()

    # Update weights
    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad

    # Zero gradients
    w.grad.zero_()
    b.grad.zero_()

print(w, b)

tensor([2.2417], requires_grad=True) tensor([0.4506], requires_grad=True)


In [62]:
import torch.nn as nn
import torch.optim as optim

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

model = nn.Linear(1,1)

optimizer = optim.Adam(model.parameters() , lr = 0.01)

criterion = nn.MSELoss()

for i in range(100):
  y_pred = model(x)
  loss = criterion(y_pred , y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

print(list(model.parameters()))

[Parameter containing:
tensor([[1.0506]], requires_grad=True), Parameter containing:
tensor([1.3240], requires_grad=True)]
