<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [3]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [4]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [5]:
torch.rand((5,6))

tensor([[0.4030, 0.8080, 0.6391, 0.7093, 0.5173, 0.1922],
        [0.2347, 0.0863, 0.3187, 0.6108, 0.8630, 0.5653],
        [0.9220, 0.6324, 0.4317, 0.9474, 0.9667, 0.8756],
        [0.2333, 0.8650, 0.8243, 0.5315, 0.6059, 0.5188],
        [0.9760, 0.7280, 0.2874, 0.8105, 0.0917, 0.6403]])

In [6]:
x = torch.arange(6)
x = x.reshape(2, 3)

In [7]:
x.view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [8]:
x = torch.arange(8)
y = torch.arange(8)
x = x.reshape(2,4)
y = y.reshape(4,2)
print(torch.matmul(x,y))

tensor([[28, 34],
        [76, 98]])


In [15]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


cuda


In [16]:
x.to("cuda")

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], device='cuda:0')

In [17]:
y.to("cpu")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [18]:
torch.matmul(x,y)

tensor([[28, 34],
        [76, 98]])

In [19]:
print(x.device)

cpu
