<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import torch

In [52]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [53]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [54]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [55]:
torch.rand((5,6))

tensor([[0.4469, 0.4188, 0.9163, 0.1729, 0.3452, 0.2595],
        [0.4903, 0.3089, 0.2344, 0.9066, 0.3671, 0.2312],
        [0.5518, 0.8989, 0.8942, 0.0413, 0.2294, 0.5662],
        [0.2398, 0.4890, 0.1818, 0.8046, 0.7667, 0.1971],
        [0.4689, 0.7844, 0.3245, 0.3084, 0.5929, 0.3218]])

In [56]:
x = torch.arange(6)
x = x.reshape(2, 3)

In [57]:
x.view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [58]:
x = torch.arange(8)
y = torch.arange(8)
x = x.reshape(2,4)
y = y.reshape(4,2)
print(torch.matmul(x,y))

tensor([[28, 34],
        [76, 98]])


In [59]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


cuda


In [60]:
x.to("cuda")

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]], device='cuda:0')

In [61]:
y.to("cpu")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [62]:
torch.matmul(x,y)

tensor([[28, 34],
        [76, 98]])

In [63]:
print(x.device)

cpu


In [64]:
x = torch.rand((2,3), requires_grad=True)
y= x**2
z = y.sum()
z.backward()

print(x)
print(x.grad)

tensor([[0.6101, 0.4598, 0.6884],
        [0.7777, 0.2787, 0.8166]], requires_grad=True)
tensor([[1.2203, 0.9195, 1.3769],
        [1.5554, 0.5574, 1.6332]])


In [65]:
import torch

# Data
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

# Model parameters
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training loop
for i in range(100):
    # Forward
    y_pred = w * x + b

    # Loss (MSE)
    loss = ((y_pred - y)**2).mean()

    # Backward
    loss.backward()

    # Update weights
    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad

    # Zero gradients
    w.grad.zero_()
    b.grad.zero_()

print(w, b)

tensor([2.0805], requires_grad=True) tensor([0.8170], requires_grad=True)


In [66]:
import torch.nn as nn
import torch.optim as optim

x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[3.0], [5.0], [7.0]])

model = nn.Linear(1,1)

optimizer = optim.Adam(model.parameters() , lr = 0.01)

criterion = nn.MSELoss()

for i in range(100):
  y_pred = model(x)
  loss = criterion(y_pred , y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

print(list(model.parameters()))

[Parameter containing:
tensor([[0.8676]], requires_grad=True), Parameter containing:
tensor([1.1048], requires_grad=True)]


In [67]:
from torch.utils.data import DataLoader

class Dataset:
  def __init__(self , x,y):
    self.x = x
    self.y = y

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = Dataset([1,2,3,4,5] , [2,4,6,8,10])

loader = DataLoader(dataset=dataset ,batch_size=2 , shuffle = True)

for x,y in loader:
  print(x,y)


tensor([2, 4]) tensor([4, 8])
tensor([1, 5]) tensor([ 2, 10])
tensor([3]) tensor([6])


In [69]:
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

class DataSet:
  def __init__(self):
    self.x = torch.randn(100, 10)
    self.y = torch.randint(0, 3, (100,))

  def __len__(self):
    return len(self.x)

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = DataSet()

loader = DataLoader( dataset,batch_size=2 , shuffle=True)

model = nn.Linear(10, 3)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters() , lr=0.01)

for epoch in range(100):
  epoch_loss =0
  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred , y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_loss += loss.item()
  print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}")

#Validation

  model.eval()
  val_loss =0

  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred , y)
    val_loss += loss.item()
  print(f"""val_loss for epoch{i} is {val_loss}""")





Epoch 1, Loss: 58.9197
val_loss for epoch99 is 54.824085116386414
Epoch 2, Loss: 55.7799
val_loss for epoch99 is 53.09333688020706
Epoch 3, Loss: 54.4850
val_loss for epoch99 is 52.50738459825516
Epoch 4, Loss: 54.4250
val_loss for epoch99 is 52.30514842271805
Epoch 5, Loss: 53.7248
val_loss for epoch99 is 52.154454708099365
Epoch 6, Loss: 53.7710
val_loss for epoch99 is 52.14295667409897
Epoch 7, Loss: 53.9908
val_loss for epoch99 is 52.07762265205383
Epoch 8, Loss: 54.1057
val_loss for epoch99 is 52.07457447052002
Epoch 9, Loss: 53.5414
val_loss for epoch99 is 52.03892892599106
Epoch 10, Loss: 53.9811
val_loss for epoch99 is 52.07796776294708
Epoch 11, Loss: 53.4327
val_loss for epoch99 is 52.03876042366028
Epoch 12, Loss: 53.8162
val_loss for epoch99 is 52.06042355298996
Epoch 13, Loss: 53.7114
val_loss for epoch99 is 52.029407262802124
Epoch 14, Loss: 53.6861
val_loss for epoch99 is 52.05539184808731
Epoch 15, Loss: 53.6389
val_loss for epoch99 is 52.029378950595856
Epoch 16, Loss:

In [74]:
class MyDataSet:
  def __init__(self):
    self.x = torch.randn(100, 10)
    self.y = torch.randint(0, 3, (100,))

  def __len__(self):
    return self.x.len()

  def __getitem__(self , index):
    return self.x[index] , self.y[index]

dataset = MyDataSet()

model = nn.Linear(10,3)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters() , lr = 0.01)

for epoch in range(100):
  epoch_loss =0
  for x, y in loader:
    y_pred = model(x)
    loss = criterion(y_pred,  y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_loss+=loss.item()
  print(f"""Loss for Epoch {epoch} is {epoch_loss}""")

  model.eval()
  val_epoch_loss=0

  for x,y in loader:
    y_pred = model(x)
    loss = criterion(y_pred,  y)
    val_epoch_loss+=loss.item()
  print(f"""Val Loss for Epoch {epoch} is {val_epoch_loss}""")

torch.save(model.state_dict() , "")
model = model.load_state_dict(torch.load(""))



Loss for Epoch 0 is 59.99402603507042
Val Loss for Epoch 0 is 54.92526423931122
Loss for Epoch 1 is 55.599458158016205
Val Loss for Epoch 1 is 53.13486969470978
Loss for Epoch 2 is 54.56612116098404
Val Loss for Epoch 2 is 52.527788043022156
Loss for Epoch 3 is 54.07263505458832
Val Loss for Epoch 3 is 52.23133999109268
Loss for Epoch 4 is 54.34019070863724
Val Loss for Epoch 4 is 52.144186556339264
Loss for Epoch 5 is 53.88106268644333
Val Loss for Epoch 5 is 52.13087314367294
Loss for Epoch 6 is 54.107198774814606
Val Loss for Epoch 6 is 52.088355123996735
Loss for Epoch 7 is 54.3209228515625
Val Loss for Epoch 7 is 52.14244729280472
Loss for Epoch 8 is 53.77252280712128
Val Loss for Epoch 8 is 52.07367151975632
Loss for Epoch 9 is 53.53861075639725
Val Loss for Epoch 9 is 52.106074929237366
Loss for Epoch 10 is 53.77814561128616
Val Loss for Epoch 10 is 52.053429305553436
Loss for Epoch 11 is 53.69441872835159
Val Loss for Epoch 11 is 52.03915625810623
Loss for Epoch 12 is 53.544695