<a href="https://colab.research.google.com/github/Krishnadev-cmd/Pytorch-Turorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.tensor([[1,2,3],[3,2,1]])

tensor([[1, 2, 3],
        [3, 2, 1]])

In [ ]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [ ]:
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.rand((5,6))

tensor([[0.4364, 0.0751, 0.0984, 0.6874, 0.6752, 0.2438],
        [0.6377, 0.1626, 0.4656, 0.2266, 0.0745, 0.7824],
        [0.4913, 0.6055, 0.3300, 0.1513, 0.3904, 0.2398],
        [0.6751, 0.4117, 0.6184, 0.9588, 0.2550, 0.5072],
        [0.6040, 0.7458, 0.9388, 0.1366, 0.1410, 0.6122]])